language: en
pipeline:
- name: WhitespaceTokenizer
  intent_tokenization_flag: true
  intent_split_symbol: +
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
- name: "MitieNLP"
  model: "data/total_word_feature_extractor.dat"  
- name: "MitieEntityExtractor"
- name: "SpacyNLP"
  model: "en_core_web_md"
  # when retrieving word vectors, this will decide if the casing
  # of the word is relevant. E.g. `hello` and `Hello` will
  # retrieve the same vector, if set to `False`. For some
  # applications and models it makes sense to differentiate
  # between these two words, therefore setting this to `True`.
- name: "SpacyEntityExtractor"
  # dimensions to extract
  dimensions: ["PERSON"]
  case_sensitive: False
- name: "DucklingHTTPExtractor"
  # url of the running duckling server
  url: "http://localhost:8000"
  # dimensions to extract
  dimensions: ["time", "number", "amount-of-money"]
  # allows you to configure the locale, by default the language is used
  locale: "en_US"
  # if not set the default timezone of Duckling is going to be used
  # needed to calculate dates from relative expressions like "tomorrow"
  timezone: "Americas/New_York"
  # Timeout for receiving response from http url of the running duckling server
  # if not set the default timeout of duckling http url is set to 3 seconds.
  timeout : 3  
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: EntitySynonymMapper
# - name: ResponseSelector
#   retrieval_intent: career_exploration
#   epochs: 100
# - name: HFTransformersNLP
#   model_name: gpt2
#   model_weights: gpt2
#   cache_dir:
policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 1
  epochs: 100
- name: RulePolicy
